"use client"

import { useForm } from "react-hook-form"
import { Bell, BellOff, Plus, Power, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import type { Admin, Room } from "@/lib/api/types"
import { createApprover, deleteApprover, toggleApproverNotifications } from "@/lib/api/admins"
import { createPolicy, deletePolicy, togglePolicy } from "@/lib/api/catalog"

const weekdays = ["周日", "周一", "周二", "周三", "周四", "周五", "周六"]
type Props = { rooms: Room[]; admins: Admin[]; reload: () => Promise<void>; report: (value?: string) => void }

export function PolicyEditor({ rooms, reload, report }: Props) {
  const form = useForm<{ room: string; day: string; start: string; end: string }>({ defaultValues: { day: "1", start: "08:00", end: "18:00" } })
  return <section><h2 className="border-b pb-3 text-lg font-semibold">房间政策</h2><form className="grid gap-2 py-4 sm:grid-cols-2 xl:grid-cols-[1fr_7rem_8rem_8rem_auto]" onSubmit={form.handleSubmit(async ({ room, day, start, end }) => { const [sh, sm] = start.split(":").map(Number); const [eh, em] = end.split(":").map(Number); try { await createPolicy(Number(room), [Number(day)], [sh, sm], [eh, em]); await reload() } catch (error) { report(error instanceof Error ? error.message : undefined) } })}><select className="h-9 rounded-md border bg-background px-2 text-sm" {...form.register("room", { required: true })}><option value="">选择房间</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-sm" {...form.register("day")} >{weekdays.map((day, index) => <option value={index} key={day}>{day}</option>)}</select><Input type="time" {...form.register("start", { required: true })} /><Input type="time" {...form.register("end", { required: true })} /><Button><Plus />添加</Button></form><div className="divide-y border-t">{rooms.flatMap((room) => room.policies.map((policy) => <div key={policy.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium">{room.name}</p><p className="text-xs text-muted-foreground">{policy.days.map((day) => weekdays[day]).join("、")} · {String(policy.startTime[0]).padStart(2, "0")}:{String(policy.startTime[1]).padStart(2, "0")}–{String(policy.endTime[0]).padStart(2, "0")}:{String(policy.endTime[1]).padStart(2, "0")} · {policy.enabled ? "启用" : "停用"}</p></div><div className="flex"><Button size="icon-sm" variant="ghost" title="切换政策状态" onClick={async () => { await togglePolicy(policy.id); await reload() }}><Power /></Button><Button size="icon-sm" variant="ghost" title="删除政策" onClick={async () => { if (window.confirm("确定删除这条房间政策吗？")) { await deletePolicy(policy.id); await reload() } }}><Trash2 /></Button></div></div>))}</div></section>
}

export function ApproverEditor({ rooms, admins, reload, report }: Props) {
  const form = useForm<{ room: string; admin: string }>()
  return <section><h2 className="border-b pb-3 text-lg font-semibold">审批人与通知</h2><form className="grid gap-2 py-4 sm:grid-cols-[1fr_1fr_auto]" onSubmit={form.handleSubmit(async ({ room, admin }) => { try { await createApprover(Number(room), Number(admin)); await reload() } catch (error) { report(error instanceof Error ? error.message : undefined) } })}><select className="h-9 rounded-md border bg-background px-2 text-sm" {...form.register("room", { required: true })}><option value="">选择房间</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-sm" {...form.register("admin", { required: true })}><option value="">选择管理员</option>{admins.map((admin) => <option key={admin.id} value={admin.id}>{admin.name} · {admin.email}</option>)}</select><Button><Plus />添加</Button></form><div className="divide-y border-t">{rooms.flatMap((room) => (room.approvers ?? []).map((approver) => { const admin = admins.find((item) => item.id === approver.adminId); return <div key={approver.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{room.name} · {admin?.name ?? `管理员 #${approver.adminId}`}</p><p className="text-xs text-muted-foreground">{approver.notificationsEnabled ? "接收新预约通知" : "通知已关闭"}</p></div><div className="flex"><Button size="icon-sm" variant="ghost" title="切换通知" onClick={async () => { await toggleApproverNotifications(approver.id); await reload() }}>{approver.notificationsEnabled ? <Bell /> : <BellOff />}</Button><Button size="icon-sm" variant="ghost" title="移除审批人" onClick={async () => { await deleteApprover(approver.id); await reload() }}><Trash2 /></Button></div></div> }))}</div></section>
}
