name: Create tagged release

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set env
              run: |
                  echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
            - name: Create release
              run: npx changelogithub-chinese
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
